name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on changes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your preferred Node.js version

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build the project
        run: |
          cd client
          npm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Grant permission to write the id-token for deployment

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # This is the branch where GitHub Pages will be deployed
          folder: client/out  # The 'out' directory will be in the 'client' folder
